<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>{{ $documentTitle }}</title>
    <style>
        @page{margin:34px 42px 70px}*{box-sizing:border-box}body{margin:0;font-family:DejaVu Sans,sans-serif;font-size:9.5px;color:#111827}table{width:100%;border-collapse:collapse}.header td{vertical-align:middle}.business{width:65%}.logo-cell{width:115px;text-align:center}.logo-cell img{max-width:105px;max-height:74px}.business-data{padding-left:14px;line-height:1.55}.business-name{color:#092a59;font-size:21px;font-weight:bold}.slogan{margin-bottom:3px;color:#6b7280;font-size:8.5px}.document-box{width:35%;padding:18px 12px;border:2px solid #174b8d;text-align:center}.document-title{color:#174b8d;font-size:15px;font-weight:bold;line-height:1.35}.document-number{margin-top:14px;font-size:16px;font-weight:bold}.blue-rule{margin:17px 0;border-top:2px solid #174b8d}.client-box{padding:9px 5px 10px;background:#f1f5f9}.section-title{margin-bottom:7px;color:#174b8d;font-size:11px;font-weight:bold}.client-box td{padding:3px 0;vertical-align:top}.client-label{width:14%}.client-value{width:50%;font-weight:bold}.sale-label{width:13%}.sale-value{width:23%;text-align:right}.items{margin-top:10px;table-layout:fixed}.items th{padding:7px 4px;background:#174b8d;color:#fff;font-size:8.5px}.items td{padding:7px 5px;border:1px solid #cbd5e1;vertical-align:middle}.center{text-align:center}.right{text-align:right}.additional{margin-top:12px}.additional-value{min-height:24px;padding:5px 7px;border:1px solid #cbd5e1}.summary{margin-top:18px}.words-cell{width:58%;padding-right:35px;vertical-align:top}.words{padding:6px;border:1px solid #cbd5e1;text-align:center;font-weight:bold}.payment{margin-top:11px;line-height:1.6}.totals-cell{width:42%;vertical-align:top}.totals td{padding:5px 6px}.total-row td{padding:8px 6px;background:#174b8d;color:#fff;font-size:13px;font-weight:bold}.bottom{margin-top:22px;page-break-inside:avoid}.qr-cell{width:28%;text-align:center;vertical-align:top}.qr-cell img{width:100px;height:100px}.qr-caption{color:#174b8d;font-size:7px;font-weight:bold}.legal-cell{width:72%;padding:17px 15px 0;color:#475569;font-size:8px;line-height:1.5;vertical-align:top}.footer{position:fixed;right:0;bottom:-48px;left:0;padding-top:9px;border-top:1px solid #174b8d;color:#4b5563;text-align:center;font-size:7.5px}
    </style>
</head>
<body>
@php
    $currency=$config->moneda?:'S/';
    $client=$venta->cliente;
    $clientDocument=$client?->ruc?:($client?->dni?:'Sin documento');
    $amountWords=app(\App\Services\Sunat\AmountInWords::class)->soles((float)$venta->total);
    $lineSubtotal=(float)$venta->detalleVentas->sum('subtotal');
    $discount=max(0,$lineSubtotal-(float)$venta->total);
@endphp
<table class="header"><tr>
    <td class="business"><table><tr><td class="logo-cell">@if($logoBase64)<img src="{{ $logoBase64 }}" alt="Logo">@endif</td><td class="business-data"><div class="business-name">{{ $config->nombre_empresa?:'DIZANY' }}</div>@if($config->lema)<div class="slogan">{{ $config->lema }}</div>@endif<strong>RUC:</strong> {{ $config->ruc?:'-' }}<br>{{ $config->direccion?:'Dirección no registrada' }}<br>@if($config->telefono)Tel: {{ $config->telefono }}@endif @if($config->telefono&&$config->correo)&nbsp; | &nbsp;@endif @if($config->correo){{ $config->correo }}@endif</td></tr></table></td>
    <td class="document-box"><div class="document-title">{{ $documentTitle }}</div><div class="document-number">{{ $venta->serie }}-{{ str_pad($venta->correlativo,8,'0',STR_PAD_LEFT) }}</div></td>
</tr></table>
<div class="blue-rule"></div>
<div class="client-box"><div class="section-title">DATOS DEL CLIENTE</div><table>
    <tr><td class="client-label">Cliente:</td><td class="client-value">{{ $client?->nombre?:'Público General' }}</td><td class="sale-label">Fecha:</td><td class="sale-value">{{ $venta->fecha->format('d/m/Y H:i') }}</td></tr>
    <tr><td class="client-label">Documento:</td><td class="client-value">{{ $client?$clientDocument:'Sin documento' }}</td><td class="sale-label">Moneda:</td><td class="sale-value">PEN - Soles</td></tr>
    <tr><td class="client-label">Dirección:</td><td class="client-value">{{ $client?->direccion?:'-' }}</td><td class="sale-label">Pago:</td><td class="sale-value">{{ ucfirst($venta->metodo_pago?:'-') }}</td></tr>
</table></div>
<table class="items"><thead><tr><th style="width:5%">ÍTEM</th><th style="width:12%">CÓD.</th><th style="width:7%">CANT.</th><th style="width:9%">UNIDAD</th><th>DESCRIPCIÓN</th><th style="width:13%">P. UNIT.</th><th style="width:9%">DTO.</th><th style="width:14%">IMPORTE</th></tr></thead><tbody>
@foreach($venta->detalleVentas as $i=>$detalle)<tr><td class="center">{{ $i+1 }}</td><td>{{ $detalle->producto?->codigo_barras?:'PROD-'.$detalle->producto_id }}</td><td class="center">{{ rtrim(rtrim(number_format($detalle->cantidad,2),'0'),'.') }}</td><td class="center">{{ strtoupper($detalle->presentacion?:'NIU') }}</td><td>{{ $detalle->producto?->nombre?:'Producto' }}</td><td class="right">{{ number_format($detalle->precio_presentacion,2) }}</td><td class="right">0.00</td><td class="right">{{ number_format($detalle->subtotal,2) }}</td></tr>@endforeach
</tbody></table>
@if($venta->informacion_adicional)<div class="additional"><div class="section-title">INFORMACIÓN ADICIONAL</div><div class="additional-value">{{ $venta->informacion_adicional }}</div></div>@endif
<table class="summary"><tr><td class="words-cell"><div class="section-title">IMPORTE EN LETRAS</div><div class="words">SON {{ $amountWords }}</div><div class="payment"><strong>Forma de pago:</strong> {{ ucfirst($venta->metodo_pago?:'-') }}@if($venta->metodo_pago==='efectivo'&&$venta->efectivo_recibido!==null)<br><strong>Efectivo recibido:</strong> {{ $currency }} {{ number_format($venta->efectivo_recibido,2) }}<br><strong>Vuelto:</strong> {{ $currency }} {{ number_format($venta->vuelto??0,2) }}@endif<br><strong>Atendido por:</strong> {{ $venta->usuario?->nombre?:'Personal de venta' }}</div></td><td class="totals-cell"><table class="totals">
    <tr><td>Subtotal</td><td class="right">{{ $currency }} {{ number_format($lineSubtotal,2) }}</td></tr><tr><td>Descuento total</td><td class="right">{{ $currency }} {{ number_format($discount,2) }}</td></tr><tr><td>Operaciones gravadas</td><td class="right">{{ $currency }} {{ number_format($venta->op_gravadas,2) }}</td></tr><tr><td>Operaciones exoneradas</td><td class="right">{{ $currency }} {{ number_format($venta->op_exoneradas,2) }}</td></tr><tr><td>{{ $venta->tax_treatment==='nrus_no_desglosado'?'Valor de venta':'Operaciones inafectas' }}</td><td class="right">{{ $currency }} {{ number_format($venta->tax_treatment==='nrus_no_desglosado'?$venta->op_nrus:$venta->op_inafectas,2) }}</td></tr><tr><td>IGV {{ number_format($venta->igv_rate,0) }}%</td><td class="right">{{ $currency }} {{ number_format($venta->igv,2) }}</td></tr><tr class="total-row"><td>IMPORTE TOTAL</td><td class="right">{{ $currency }} {{ number_format($venta->total,2) }}</td></tr>
</table></td></tr></table>
<table class="bottom"><tr><td class="qr-cell"><img src="data:image/svg+xml;base64,{{ $qr }}" alt="Código QR"><div class="qr-caption">CÓDIGO QR DEL COMPROBANTE</div></td><td class="legal-cell">Representación impresa de {{ strtolower($documentTitle) }}.<br>Conserve este documento para sus consultas. La información y el código QR se generan con los datos registrados por el sistema.@if(!$isElectronic)<br><strong>Documento interno de control comercial.</strong>@endif</td></tr></table>
<div class="footer">Representación impresa del comprobante. Gracias por su compra.</div>
</body></html>
