<!DOCTYPE html>
<html lang="es"><head><meta charset="UTF-8"><title>{{ $documentTitle }}</title><style>
@page{margin:24px 28px 145px}*{box-sizing:border-box}body{margin:0;font-family:DejaVu Sans,sans-serif;font-size:10px;color:#16243a}table{width:100%;border-collapse:collapse}.brand-table td{vertical-align:middle}.brand-cell{width:50%;padding:10px 20px;text-align:center}.issuer-cell{width:50%;padding:14px 20px;border-left:2px solid #d7a51d;background:#f7f9fc;line-height:1.65}.logo img{max-width:72px;max-height:64px}.company-name{margin-top:2px;color:#092a59;font-size:23px;font-weight:bold;letter-spacing:.8px}.slogan{margin-top:3px;color:#7a6030;font-size:9px}.issuer-name{color:#092a59;font-size:13px;font-weight:bold}.gold-rule{margin:15px 0 13px;border-top:1px solid #d7a51d}.document-title{text-align:center;color:#092a59;font-size:18px;font-weight:bold}.document-number{width:230px;margin:7px auto 13px;padding:7px;text-align:center;border-radius:4px;background:#092a59;color:#fff;font-size:15px;font-weight:bold}.meta td{padding:4px 8px;border:1px solid #dce3ed}.meta .label{width:18%;color:#53647a;font-weight:bold;background:#f7f9fc}.section{margin-top:12px}.items th{padding:7px 6px;background:#092a59;color:#fff;font-size:9px}.items td{padding:7px 6px;border-bottom:1px solid #dce3ed}.items tbody tr:nth-child(even){background:#f8fafc}.center{text-align:center}.right{text-align:right}.summary-layout{margin-top:13px}.payment-box{width:47%;padding:10px;border:1px solid #dce3ed;background:#f8fafc;line-height:1.7;vertical-align:top}.spacer{width:6%}.totals-box{width:47%;vertical-align:top}.totals td{padding:5px 9px;border-bottom:1px solid #e2e8f0}.grand-total td{padding:8px 9px;border:0;background:#092a59;color:#fff;font-size:14px;font-weight:bold}.document-footer{position:fixed;left:0;right:0;bottom:-120px;height:112px}.footer-layout{border-top:1px solid #d7a51d}.footer-layout td{padding-top:8px;vertical-align:middle}.qr-cell{width:25%;text-align:center}.qr-cell img{width:78px;height:78px}.legal-cell{width:48%;padding-left:10px!important;color:#53647a;font-size:8px;line-height:1.45}.cashier-cell{width:27%;text-align:center;font-size:9px}.thanks{margin-top:7px;padding:6px;text-align:center;border-bottom:5px solid #092a59;color:#092a59;font-size:12px;font-weight:bold}.internal-note{margin-top:3px;text-align:center;color:#8a5b00;font-size:8px}
</style></head><body>
@php
$currency=$config->moneda?:'S/';$client=$venta->cliente;$clientDocument=$client?->ruc?:($client?->dni?:'-');$operationAmount=(float)($venta->op_gravadas+$venta->op_exoneradas+$venta->op_inafectas+$venta->op_nrus);$operationLabel=match($venta->tax_treatment){'exonerada'=>'Op. Exoneradas','inafecta'=>'Op. Inafectas','nrus_no_desglosado'=>'Valor de venta',default=>'Op. Gravadas'};
@endphp
<table class="brand-table"><tr><td class="brand-cell">@if($logoBase64)<div class="logo"><img src="{{ $logoBase64 }}" alt="Logo"></div>@endif<div class="company-name">{{ $config->nombre_empresa?:'DIZANY' }}</div>@if($config->lema)<div class="slogan">{{ $config->lema }}</div>@endif</td><td class="issuer-cell"><span class="issuer-name">Datos del negocio</span><br><strong>RUC:</strong> {{ $config->ruc?:'-' }}<br>{{ $config->direccion?:'Dirección no registrada' }}<br>@if($config->telefono)Tel: {{ $config->telefono }}<br>@endif @if($config->correo){{ $config->correo }}@endif</td></tr></table>
<div class="gold-rule"></div><div class="document-title">{{ $documentTitle }}</div><div class="document-number">{{ $venta->serie }}-{{ str_pad($venta->correlativo,8,'0',STR_PAD_LEFT) }}</div>
<table class="meta"><tr><td class="label">Cliente</td><td>{{ $client?->nombre?:'Consumidor final' }}</td><td class="label">DNI / RUC</td><td>{{ $clientDocument }}</td></tr><tr><td class="label">Dirección</td><td>{{ $client?->direccion?:'-' }}</td><td class="label">Fecha</td><td>{{ $venta->fecha->format('d/m/Y H:i') }}</td></tr><tr><td class="label">Forma de pago</td><td>{{ ucfirst($venta->metodo_pago?:'-') }}</td><td class="label">Moneda</td><td>{{ $currency }} - Soles</td></tr></table>
<div class="section"><table class="items"><thead><tr><th style="width:7%">#</th><th>Descripción</th><th style="width:18%">Cantidad</th><th style="width:17%">P. Unitario</th><th style="width:17%">Importe</th></tr></thead><tbody>@foreach($venta->detalleVentas as $i=>$detalle)<tr><td class="center">{{ $i+1 }}</td><td>{{ $detalle->producto?->nombre?:'Producto' }}</td><td class="center">{{ $detalle->cantidad }} {{ ucfirst($detalle->presentacion) }}</td><td class="right">{{ $currency }} {{ number_format($detalle->precio_presentacion,2) }}</td><td class="right">{{ $currency }} {{ number_format($detalle->subtotal,2) }}</td></tr>@endforeach</tbody></table></div>
<table class="summary-layout"><tr><td class="payment-box"><strong style="color:#092a59">Método de pago</strong><br>{{ ucfirst($venta->metodo_pago?:'-') }}<br>Estado: {{ ucfirst($venta->estado?:'-') }}<br>Atendido por: {{ $venta->usuario?->nombre?:'Personal de venta' }}</td><td class="spacer"></td><td class="totals-box"><table class="totals"><tr><td>{{ $operationLabel }}</td><td class="right">{{ $currency }} {{ number_format($operationAmount,2) }}</td></tr>@if($venta->tax_treatment==='gravada')<tr><td>IGV ({{ number_format($venta->igv_rate,2) }}%)</td><td class="right">{{ $currency }} {{ number_format($venta->igv,2) }}</td></tr>@endif<tr class="grand-total"><td>TOTAL</td><td class="right">{{ $currency }} {{ number_format($venta->total,2) }}</td></tr></table></td></tr></table>
<div class="document-footer"><table class="footer-layout"><tr><td class="qr-cell"><img src="data:image/svg+xml;base64,{{ $qr }}" alt="Código QR"></td><td class="legal-cell">Representación impresa de {{ strtolower($documentTitle) }}.<br>Conserve este documento para sus consultas. La información y el código QR se generan con los datos registrados por el sistema.</td><td class="cashier-cell"><strong>Atendido por</strong><br>{{ $venta->usuario?->nombre?:'Personal de venta' }}</td></tr></table>@if(!$isElectronic)<div class="internal-note">Documento interno de control comercial.</div>@endif<div class="thanks">¡Gracias por su compra!</div></div>
</body></html>
