<!DOCTYPE html>
<html lang="es"><head><meta charset="UTF-8"><title>{{ $documentTitle }}</title><style>
@page{margin:0}*{box-sizing:border-box}body{margin:0;padding:{{ $ticketWidth<=58?'2.3':'3.2' }}mm;font-family:DejaVu Sans,sans-serif;font-size:{{ $ticketWidth<=58?'7.2':'8.5' }}px;line-height:1.35;color:#111}table{width:100%;border-collapse:collapse}.header-table td{vertical-align:middle}.brand-column{width:46%;padding-right:{{ $ticketWidth<=58?'4':'7' }}px;text-align:center}.issuer-column{width:54%;padding-left:{{ $ticketWidth<=58?'4':'7' }}px;border-left:1px solid #d7a51d;text-align:left}.logo img{max-width:{{ $ticketWidth<=58?'38':'48' }}px;max-height:{{ $ticketWidth<=58?'36':'45' }}px}.company{margin-top:1px;color:#092a59;font-size:{{ $ticketWidth<=58?'10.5':'13.5' }}px;font-weight:bold;line-height:1.1}.slogan{margin-top:2px;color:#7a6030;font-size:{{ $ticketWidth<=58?'5.2':'6.6' }}px;line-height:1.2}.issuer{font-size:{{ $ticketWidth<=58?'5.9':'7' }}px;line-height:1.45}.document-header{text-align:center}.rule{margin:5px 0;border-top:1px dashed #111}.doc-title{font-size:{{ $ticketWidth<=58?'9':'10.5' }}px;font-weight:bold}.doc-number{display:inline-block;margin:3px 0;padding:3px 7px;border-radius:2px;background:#092a59;color:#fff;font-size:{{ $ticketWidth<=58?'9':'11' }}px;font-weight:bold}.info td{padding:1px 0;vertical-align:top}.info .label{width:26%;font-weight:bold}.items{table-layout:fixed}.items th{padding:3px 1px;border-top:1px solid #111;border-bottom:1px solid #111;font-size:{{ $ticketWidth<=58?'6.1':'7' }}px}.items td{padding:3px 1px;border-bottom:1px dotted #777;vertical-align:top;overflow-wrap:break-word}.items th:nth-child(1),.items td:nth-child(1){width:43%}.items th:nth-child(2),.items td:nth-child(2){width:13%}.items th:nth-child(3),.items td:nth-child(3){width:19%}.items th:nth-child(4),.items td:nth-child(4){width:25%}.center{text-align:center}.right{text-align:right}.totals td{padding:2px 0}.grand-total td{padding:5px 0;border-top:1px solid #111;border-bottom:1px solid #111;font-size:{{ $ticketWidth<=58?'10':'12' }}px;font-weight:bold}.ticket-footer{page-break-inside:avoid}.qr{margin-top:5px;text-align:center}.qr img{width:{{ $ticketWidth<=58?'58':'72' }}px;height:{{ $ticketWidth<=58?'58':'72' }}px}.legal{margin-top:2px;text-align:center;font-size:{{ $ticketWidth<=58?'6.2':'7' }}px}.thanks{margin-top:5px;padding:5px 0 1px;border-top:1px dashed #111;text-align:center;color:#092a59;font-size:{{ $ticketWidth<=58?'8':'9.5' }}px;font-weight:bold}
</style></head><body>
@php
$currency=$config->moneda?:'S/';$client=$venta->cliente;$clientDocument=$client?->ruc?:($client?->dni?:'-');$operationAmount=(float)($venta->op_gravadas+$venta->op_exoneradas+$venta->op_inafectas+$venta->op_nrus);$operationLabel=match($venta->tax_treatment){'exonerada'=>'Op. Exoneradas','inafecta'=>'Op. Inafectas','nrus_no_desglosado'=>'Valor venta',default=>'Op. Gravadas'};
@endphp
<table class="header-table"><tr><td class="brand-column">@if($logoBase64)<div class="logo"><img src="{{ $logoBase64 }}" alt="Logo"></div>@endif<div class="company">{{ $config->nombre_empresa?:'DIZANY' }}</div>@if($config->lema)<div class="slogan">{{ $config->lema }}</div>@endif</td><td class="issuer-column"><div class="issuer"><strong>RUC: {{ $config->ruc?:'-' }}</strong><br>{{ $config->direccion?:'Dirección no registrada' }}@if($config->telefono)<br>Tel: {{ $config->telefono }}@endif @if($config->correo)<br>{{ $config->correo }}@endif</div></td></tr></table><div class="document-header"><div class="rule"></div><div class="doc-title">{{ $documentTitle }}</div><div class="doc-number">{{ $venta->serie }}-{{ str_pad($venta->correlativo,8,'0',STR_PAD_LEFT) }}</div></div>
<div class="rule"></div><table class="info"><tr><td class="label">Cliente:</td><td>{{ $client?->nombre?:'Consumidor final' }}</td></tr><tr><td class="label">DNI/RUC:</td><td>{{ $clientDocument }}</td></tr><tr><td class="label">Fecha:</td><td>{{ $venta->fecha->format('d/m/Y H:i') }}</td></tr><tr><td class="label">Pago:</td><td>{{ ucfirst($venta->metodo_pago?:'-') }}</td></tr></table><div class="rule"></div>
<table class="items"><thead><tr><th>Descripción</th><th>Cant.</th><th class="right">P/U</th><th class="right">Importe</th></tr></thead><tbody>@foreach($venta->detalleVentas as $detalle)<tr><td>{{ $detalle->producto?->nombre?:'Producto' }}</td><td class="center">{{ $detalle->cantidad }}</td><td class="right">{{ number_format($detalle->precio_presentacion,2) }}</td><td class="right">{{ number_format($detalle->subtotal,2) }}</td></tr>@endforeach</tbody></table><div class="rule"></div>
<table class="totals"><tr><td>{{ $operationLabel }}</td><td class="right">{{ $currency }} {{ number_format($operationAmount,2) }}</td></tr>@if($venta->tax_treatment==='gravada')<tr><td>IGV ({{ number_format($venta->igv_rate,2) }}%)</td><td class="right">{{ $currency }} {{ number_format($venta->igv,2) }}</td></tr>@endif<tr class="grand-total"><td>TOTAL</td><td class="right">{{ $currency }} {{ number_format($venta->total,2) }}</td></tr></table><div class="ticket-footer"><div class="legal">Atendido por: {{ $venta->usuario?->nombre?:'Personal de venta' }}</div><div class="qr"><img src="data:image/svg+xml;base64,{{ $qr }}" alt="Código QR"></div><div class="legal">Representación impresa de {{ strtolower($documentTitle) }}.@if(!$isElectronic)<br>Documento interno de control comercial.@endif</div><div class="thanks">¡Gracias por su compra!</div></div>
</body></html>
