<!DOCTYPE html>
<html lang="es"><head><meta charset="UTF-8"><title>{{ $documentTitle }}</title><style>
@page{margin:0}*{box-sizing:border-box}body{margin:0;padding:{{ $ticketWidth<=58?'2.2':'3' }}mm;font-family:DejaVu Sans,sans-serif;font-size:{{ $ticketWidth<=58?'6.8':'8.1' }}px;line-height:1.35;color:#111}table{width:100%;border-collapse:collapse}.header td{vertical-align:middle}.brand{width:43%;padding-right:5px;text-align:center}.issuer{width:57%;padding-left:6px;border-left:1px solid #174b8d;line-height:1.45}.logo img{max-width:{{ $ticketWidth<=58?'34':'44' }}px;max-height:{{ $ticketWidth<=58?'32':'42' }}px}.company{color:#092a59;font-size:{{ $ticketWidth<=58?'9.5':'12' }}px;font-weight:bold}.slogan{color:#6b7280;font-size:{{ $ticketWidth<=58?'4.8':'6.1' }}px}.rule{margin:5px 0;border-top:1px dashed #111}.document{text-align:center}.doc-title{font-size:{{ $ticketWidth<=58?'8.4':'10.2' }}px;font-weight:bold}.doc-number{margin-top:2px;font-size:{{ $ticketWidth<=58?'9':'11' }}px;font-weight:bold}.info td{padding:1px 0;vertical-align:top}.info-label{width:24%;font-weight:bold}.product{padding:4px 1px;border-bottom:1px dashed #555}.product-name{font-weight:bold}.product-line{margin-top:2px}.product-amount{float:right}.right{text-align:right}.totals td{padding:2px 0}.total-row td{padding:5px 0;border-top:1px solid #111;border-bottom:1px solid #111;font-size:{{ $ticketWidth<=58?'9.2':'11.2' }}px;font-weight:bold}.words{padding-top:4px;text-align:center;font-size:{{ $ticketWidth<=58?'5.9':'7' }}px;font-weight:bold}.payment{padding:4px 0;text-align:center}.additional{padding:4px 0}.footer{page-break-inside:avoid;text-align:center}.qr img{width:{{ $ticketWidth<=58?'56':'70' }}px;height:{{ $ticketWidth<=58?'56':'70' }}px}.legal{margin-top:2px;font-size:{{ $ticketWidth<=58?'5.7':'6.8' }}px}.thanks{margin-top:4px;font-style:italic}
</style></head><body>
@php
$currency=$config->moneda?:'S/';$client=$venta->cliente;$clientDocument=$client?->ruc?:($client?->dni?:'Sin documento');$amountWords=app(\App\Services\Sunat\AmountInWords::class)->soles((float)$venta->total);$lineSubtotal=(float)$venta->detalleVentas->sum('subtotal');$discount=max(0,$lineSubtotal-(float)$venta->total);
@endphp
<table class="header"><tr><td class="brand">@if($logoBase64)<div class="logo"><img src="{{ $logoBase64 }}" alt="Logo"></div>@endif<div class="company">{{ $config->nombre_empresa?:'DIZANY' }}</div>@if($config->lema)<div class="slogan">{{ $config->lema }}</div>@endif</td><td class="issuer"><strong>RUC: {{ $config->ruc?:'-' }}</strong><br>{{ $config->direccion?:'Dirección no registrada' }}@if($config->telefono)<br>Tel: {{ $config->telefono }}@endif @if($config->correo)<br>{{ $config->correo }}@endif</td></tr></table>
<div class="rule"></div><div class="document"><div class="doc-title">{{ $documentTitle }}</div><div class="doc-number">{{ $venta->serie }}-{{ str_pad($venta->correlativo,8,'0',STR_PAD_LEFT) }}</div></div><div class="rule"></div>
<table class="info"><tr><td class="info-label">Fecha:</td><td>{{ $venta->fecha->format('d/m/Y H:i') }}</td></tr><tr><td class="info-label">Cajero:</td><td>{{ $venta->usuario?->nombre?:'Personal de venta' }}</td></tr><tr><td class="info-label">Cliente:</td><td>{{ $client?->nombre?:'Público General' }}</td></tr><tr><td class="info-label">DNI/RUC:</td><td>{{ $client?$clientDocument:'Sin documento' }}</td></tr></table><div class="rule"></div>
@foreach($venta->detalleVentas as $detalle)<div class="product"><div class="product-name">{{ rtrim(rtrim(number_format($detalle->cantidad,2),'0'),'.') }} x {{ $detalle->producto?->nombre?:'Producto' }}</div><div class="product-line">U.M. {{ strtoupper($detalle->presentacion?:'NIU') }} &nbsp; P.Unit {{ $currency }}{{ number_format($detalle->precio_presentacion,2) }} <span class="product-amount">{{ $currency }}{{ number_format($detalle->subtotal,2) }}</span></div></div>@endforeach
<table class="totals"><tr><td>Subtotal:</td><td class="right">{{ $currency }}{{ number_format($lineSubtotal,2) }}</td></tr><tr><td>Descuento total:</td><td class="right">{{ $currency }}{{ number_format($discount,2) }}</td></tr><tr><td>Operaciones gravadas:</td><td class="right">{{ $currency }}{{ number_format($venta->op_gravadas,2) }}</td></tr><tr><td>Operaciones exoneradas:</td><td class="right">{{ $currency }}{{ number_format($venta->op_exoneradas,2) }}</td></tr><tr><td>{{ $venta->tax_treatment==='nrus_no_desglosado'?'Valor de venta:':'Operaciones inafectas:' }}</td><td class="right">{{ $currency }}{{ number_format($venta->tax_treatment==='nrus_no_desglosado'?$venta->op_nrus:$venta->op_inafectas,2) }}</td></tr><tr><td>IGV ({{ number_format($venta->igv_rate,0) }}%):</td><td class="right">{{ $currency }}{{ number_format($venta->igv,2) }}</td></tr><tr class="total-row"><td>IMPORTE TOTAL:</td><td class="right">{{ $currency }}{{ number_format($venta->total,2) }}</td></tr></table>
<div class="words">SON {{ $amountWords }}</div><div class="payment">Pago: {{ ucfirst($venta->metodo_pago?:'-') }}@if($venta->metodo_pago==='efectivo'&&$venta->efectivo_recibido!==null)<br>Recibido: {{ $currency }}{{ number_format($venta->efectivo_recibido,2) }} &nbsp; Vuelto: {{ $currency }}{{ number_format($venta->vuelto??0,2) }}@endif</div>
@if($venta->informacion_adicional)<div class="rule"></div><div class="additional"><strong>Información adicional:</strong><br>{{ $venta->informacion_adicional }}</div>@endif
<div class="rule"></div><div class="footer"><div class="qr"><img src="data:image/svg+xml;base64,{{ $qr }}" alt="Código QR"></div><div class="legal">Representación impresa de {{ strtolower($documentTitle) }}.@if(!$isElectronic)<br>Documento interno de control comercial.@endif</div><div class="thanks">¡Gracias por su preferencia!</div><div>{{ $config->nombre_empresa?:'DIZANY' }}</div></div>
</body></html>
